theme: jekyll-theme-cayman
title: Stack Overflow Survey Analysis - a Data Scientist perspective
description: Analysis of the results of Stack Overflow Surveys from the perspecitve of Data Science field
